# Site settings
name: Ssf的个人博客
email: 1018484601@qq.com
author: SSF
github: https://github.com/waanan
baseurl: ""
description: To be continued！
meta_description: Ssf的个人博客

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: waanan

# Build settings
# markdown: kramdown

baidu_analysis: 4366f0ca1b7751ca8e068d531863f2f8